### ISSUE TITLE
[BACKLOG] Logging out

### ISSUE THREAD

**Issue by riflowth** [cpe-kmutt-student/bangmod-hackathon-2023#35]
### WE NEED A LOGOUT BUTTON

NO NO NO WE DON'T NEED TO BE STUCK IN BANGMOD HACKATHON FOREVER
NO NO NO WE DON'T NEED TO BE STUCK IN BANGMOD HACKATHON FOREVER
NO NO NO WE DON'T NEED TO BE STUCK IN BANGMOD HACKATHON FOREVER
NO NO NO WE DON'T NEED TO BE STUCK IN BANGMOD HACKATHON FOREVER

![NO LOGOUT](https://i.pinimg.com/originals/6f/d0/2c/6fd02ca9f8e490f8c38e9a7c0c28225f.jpg)

**Comment by nut1414** [comment]
**if you die in Bangmod Hackathon, you die in *real life*.**

**Comment by riflowth** [comment]
![SAO Death](https://i.pinimg.com/originals/e8/42/02/e84202cd5853ae5ea3f97adc854f6ae9.gif)

**Comment by Porama6400** [comment]
> **if you die in Bangmod Hackathon, you die in _real life_.**

Lie lie lie lie 
No proof
No proof
No proof

**Comment by riflowth** [comment]
Congrats 🎉 Now we can log out
