### ISSUE TITLE
[BUG] Backend reject the request of the valid saving form 

### ISSUE THREAD

**Issue by XiaoXuxxxx** [cpe-kmutt-student/bangmod-hackathon-2023#90]
**Describe the bug**
When submit the form via submit button. The backend response with status code 500 with message `Submit complete but all input not completed` although every from is filled and valid.

**To Reproduce**
1. fill every input including file upload **EXCEPT** the `ชื่อกลาง` and `middle name` field
2. submit by pressing `ยืนยันการบันทึกข้อมูล` button
3. accept the prompt to confirm saving by clicking `บันทึก` button
4. the form input is disabled but doesn't alert that the form is submitted. If we inspect the network request, it show that the backend rejected the data

**Expected behavior**
The backend should response with 2xx if the form that manually submitted is valid

**Screenshots**
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/73125291/197535424-76fe5947-528a-4e6f-980f-0ee1bd0786c7.png">

**Comment by riflowth** [comment]
Resolved Thanks, MVP @XiaoXuxxxx 🥇
