### ISSUE TITLE
[BUG] Backend can't handle file that have polluted name

### ISSUE THREAD

**Issue by XiaoXuxxxx** [cpe-kmutt-student/bangmod-hackathon-2023#91]
**Describe the bug**

**To Reproduce**
1. Upload file that have very very long name (233 characters long) to file input box.
2. The web page show the `Cancel` button but not have the link to access uploaded file. The backend response with status code 500 with message of prisma error `nInvalid prisma.file.upsert() invocation:\n\n\nThe provided value for the column is too long for the column's type. Column: originalName`

**Expected behavior**
Backend should clean and accept the file that have polluted file name

**Screenshot**
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/73125291/197542044-1f238861-3de6-4025-92a4-7b2fa2f5e058.png">

**Comment by riflowth** [comment]
Fixes on e0c592b781fc7e335c2fcf06fb204ead484195df
